=== sys-git/epyrpc/test/config/integration_config/master/config/validation/distribution.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
 elementFormDefault="qualified"
 targetNamespace="distribution"
 xmlns:distribution = "distribution">
  <xs:element name="distribution">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="distribution:SourceDistribution"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="SourceDistribution">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="1" minOccurs="1" ref="distribution:sourceExtensions"/>
        <xs:element maxOccurs="1" minOccurs="1" ref="distribution:transferChunkSize"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="sourceExtensions">
    <xs:complexType>
        <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="unbounded" ref="distribution:extension" />
        </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="extension" type="xs:string"/>
  <xs:element name="transferChunkSize" type="xs:integer"/>
</xs:schema>

=== sys-git/epyrpc/test/config/executionOrganiser/config/distribution.xml
<distribution
    xmlns="distribution"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="distribution validation/distribution.xsd">
    <SourceDistribution>
        <sourceExtensions>
            <extension>*.py</extension>
            <extension>*.cfg</extension>
            <extension>*.xml</extension>
            <extension>*.ini</extension>
        </sourceExtensions>
        <transferChunkSize>1024</transferChunkSize>
    </SourceDistribution>
</distribution>
