=== sys-git/epyrpc/test/config/integration_config/master/config/validation/filters.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
 elementFormDefault="qualified"
 targetNamespace="filters"
 xmlns:filters = "filters">
  <xs:element name="filters">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="filters:TestFilter"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="filters:PriorityFilter" />
        <xs:element minOccurs="0" maxOccurs="1" ref="filters:TestPackFilter" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="TestFilter">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="direction" minOccurs="1" maxOccurs="1">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="include"/>
              <xs:enumeration value="exclude"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element minOccurs="1" maxOccurs="1" ref="filters:parameter"/>
        <xs:element minOccurs="1" maxOccurs="1" ref="filters:values"/>
      </xs:sequence>
      <xs:attribute name="enabled" use="required" type="xs:boolean"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="PriorityFilter">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="direction" minOccurs="1" maxOccurs="1">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="ascending"/>
              <xs:enumeration value="descending"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element minOccurs="1" maxOccurs="1"  ref="filters:parameter"/>
        <xs:element ref="filters:values"/>
      </xs:sequence>
      <xs:attribute name="enabled" use="required" type="xs:boolean"/>
    </xs:complexType>
  </xs:element> 
  <xs:element name="TestPackFilter">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="filters:locations" />
        </xs:sequence>
        <xs:attribute name="enabled" type="xs:boolean" />
    </xs:complexType>
  </xs:element>
  <xs:element name="parameter">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="testClass"/>
        <xs:enumeration value="testMethod"/>
        <xs:enumeration value="testId"/>
        <xs:enumeration value="testFile"/>
        <xs:enumeration value="testStatus"/>
        <xs:enumeration value="environment"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="values">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="filters:value"/>
      </xs:sequence>
      <xs:attribute name="type">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="literal" />
                <xs:enumeration value="regex" />
            </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="value">
    <xs:complexType mixed="true">
      <xs:attribute name="type">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="literal" />
                <xs:enumeration value="regex" />
            </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="locations">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="location" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== sys-git/epyrpc/test/config/testFilters2/config/filters.xml
<filters xmlns="filters" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="filters validation/filters.xsd">
    <TestFilter enabled="false">
        <direction>include</direction>
        <parameter>testClass</parameter>
        <values>
            <value>class1</value>
            <value>class2</value>
        </values>
    </TestFilter>
    <TestFilter enabled="false">
        <direction>exclude</direction>
        <parameter>testClass</parameter>
        <values>
            <value>eqjdia</value>
        </values>
    </TestFilter>
    <TestFilter enabled="false">
        <direction>exclude</direction>
        <parameter>testMethod</parameter>
        <values>
            <value>testi</value>
        </values>
    </TestFilter>
    <PriorityFilter enabled="true">
        <direction>ascending</direction>
        <parameter>testClass</parameter>
        <values>
            <value>class1</value>
        </values>
    </PriorityFilter>
</filters>

=== sys-git/epyrpc/test/config/testGatherManager4/config/filters.xml
<filters
    xmlns="filters"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="filters validation/filters.xsd">
 <TestFilter enabled="true">
  <direction>exclude</direction>
  <parameter>testMethod</parameter>
  <values>
   <value>testMetdshodfsdf3231</value>
  </values>
 </TestFilter>
 <TestFilter enabled="true">
  <direction>include</direction>
  <parameter>testClass</parameter>
  <values>
   <value>TestExample8</value>
  </values>
 </TestFilter>
 <PriorityFilter enabled="true">
  <direction>descending</direction>
  <parameter>testMethod</parameter>
  <values>
  </values>
 </PriorityFilter>
</filters>

=== sys-git/epyrpc/test/config/invalidIntegration/master/config/filters.xml
<filters
    xmlns="filters"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="filters validation/filters.xsd">
 <TestFilter enabled="false">
  <direction>include</direction>
  <parameter>testId</parameter>
  <values>
   <value>2</value>
  </values>
 </TestFilter>
 <TestFilter enabled="false">
  <direction>include</direction>
  <parameter>testClass</parameter>
  <values>
   <value>TestMediaRouter</value>
  </values>
 </TestFilter>
</filters>

=== sys-git/epyrpc/test/config/testFilters1/config/filters.xml
<filters
    xmlns="filters"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="filters validation/filters.xsd">
 <TestFilter enabled="true">
  <direction>include</direction>
  <parameter>testClass</parameter>
  <values>
   <value>class1</value>
   <value>eqjdia</value>
  </values>
 </TestFilter>
 <TestFilter enabled="true">
  <direction>exclude</direction>
  <parameter>testClass</parameter>
  <values>
   <value>eqjdia</value>
  </values>
 </TestFilter>
 <TestFilter enabled="false">
  <direction>exclude</direction>
  <parameter>testClass</parameter>
  <values>
   <value>dvb-t2</value>
  </values>
 </TestFilter>
</filters>

=== sys-git/epyrpc/test/config/testFilters3/config/filters.xml
<?xml version='1.0' encoding="utf-8"?>
<filters
    xmlns="filters"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="filters validation/filters.xsd">
 <TestFilter enabled="false">
  <direction>include</direction>
  <parameter>testFile</parameter>
  <values>
   <value>/test/t.py</value>
  </values>
 </TestFilter>
 <TestFilter enabled="true">
  <direction>exclude</direction>
  <parameter>testClass</parameter>
  <values>
   <value>class1</value>
  </values>
 </TestFilter>
 <PriorityFilter enabled="true">
  <direction>ascending</direction>
  <parameter>testMethod</parameter>
  <values>
  </values>
 </PriorityFilter>
</filters>

=== sys-git/epyrpc/test/config/executionOrganiser/config/filters.xml
<filters xmlns="filters" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="filters validation/filters.xsd">
    <TestFilter enabled="false">
        <direction>include</direction>
        <parameter>testStatus</parameter>
        <values>
            <value>inuse</value>
            <value>youviewreview</value>
        </values>
    </TestFilter>
    <TestPackFilter enabled="false">
        <locations>
            <location>/home/smoky/Desktop/soak.testpack</location>
        </locations>
    </TestPackFilter>
</filters>

=== sys-git/epyrpc/test/config/testFilterRegexExclude/config/filters.xml
<filters xmlns="filters" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="filters validation/filters.xsd">
    <TestFilter enabled="true">
        <direction>exclude</direction>
        <parameter>testClass</parameter>
        <values type="regex">
            <value type="literal">tclass</value>
            <value>class[0-9]+</value>
        </values>
    </TestFilter>
    <PriorityFilter enabled="true">
        <direction>ascending</direction>
        <parameter>environment</parameter>
        <values>
            <value type="literal">dvb-ta</value>
            <value type="regex">dvb-t[0-9]+</value>
        </values>
    </PriorityFilter>
</filters>

=== sys-git/epyrpc/test/config/testFilters5/config/filters.xml
<filters
    xmlns="filters"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="filters validation/filters.xsd">
 <TestFilter enabled="true">
  <direction>include</direction>
  <parameter>testFile</parameter>
  <values>
   <value>/test/t.py</value>
   <value>/t/test.py</value>
  </values>
 </TestFilter>
 <TestFilter enabled="true">
  <direction>exclude</direction>
  <parameter>testFile</parameter>
  <values>
   <value>/t/test.py</value>
  </values>
 </TestFilter>
 <TestFilter enabled="false">
  <direction>exclude</direction>
  <parameter>testFile</parameter>
  <values>
   <value>/test/t.py</value>
  </values>
 </TestFilter>
 <PriorityFilter enabled="false">
  <direction>descending</direction>
  <parameter>testClass</parameter>
  <values>
  </values>
 </PriorityFilter>
</filters>
