=== sys-git/epyrpc/test/config/validation/logCapture.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    elementFormDefault="qualified"
    targetNamespace="logCapture"
    xmlns:logCapture = "logCapture">
  <xs:element name="logCapture">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="logCapture:logTypes"/>
        <xs:element ref="logCapture:logTransfer"/>
        <xs:element ref="logCapture:tmpStorageLocation" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="logTypes">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="logCapture:stdout"/>
        <xs:element ref="logCapture:stderr"/>
        <xs:element ref="logCapture:dbus"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="logTransfer">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="logCapture:chunkSize"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="stdout" type="logCapture:stdoutValidation" />
  <xs:element name="stderr" type="logCapture:stderrValidation" />
  <xs:element name="dbus" type="logCapture:dbusValidation" />
  <xs:element name="chunkSize" type="logCapture:chunkSizeValidation" />
  <xs:complexType name="stdoutValidation">
    <xs:attribute name="enabled" use="required" type="xs:boolean"/>
  </xs:complexType>
  <xs:complexType name="stderrValidation">
    <xs:attribute name="enabled" use="required" type="xs:boolean"/>
  </xs:complexType>
  <xs:complexType name="dbusValidation">
    <xs:simpleContent>
        <xs:extension base="xs:string">
            <xs:attribute name="enabled" use="required" type="xs:boolean"/>
        </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:simpleType name="chunkSizeValidation">
        <xs:restriction base="xs:integer"/>
  </xs:simpleType>
  <xs:element name="tmpStorageLocation" type="xs:string"/>
</xs:schema>

=== sys-git/epyrpc/test/config/jobCleanup/config/logCapture.xml
<logCapture
    xmlns="logCapture"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="logCapture validation/logCapture.xsd">
    <logTypes>
        <stdout enabled="true"/>
        <stderr enabled="true"/>
        <dbus enabled="true">/usr/bin/dbus-monitor</dbus>
    </logTypes>
    <logTransfer>
        <chunkSize>1024</chunkSize>
    </logTransfer>
    <tmpStorageLocation>/tmp</tmpStorageLocation>
</logCapture>
