=== sys-git/epyrpc/test/config/validation/routes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified" targetNamespace="routes"
    xmlns:routes="routes">
    <xs:element name="routes">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="1"
                    ref="routes:route" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="route">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="routes:host" />
                <xs:element ref="routes:port" />
            </xs:sequence>
            <xs:attribute name="enabled" use="required"
                type="xs:boolean" />
            <xs:attribute name="name" use="required"
                type="routes:nameValidation" />
        </xs:complexType>
        <xs:unique name="uniqueNames">
            <xs:selector xpath="routes/route" />
            <xs:field xpath="@name"></xs:field>
        </xs:unique>
        <xs:unique name="uniqueIPs">
            <xs:selector xpath="host" />
            <xs:field xpath="." />
        </xs:unique>
    </xs:element>
    <xs:element name="host">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern
                    value="^(([1-9]?[0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([1-9]?[0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])$" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="port">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="1024" />
                <xs:maxInclusive value="65535" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:simpleType name="nameValidation">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z0-9_\.\-]+" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== sys-git/epyrpc/test/config/executionOrganiser/config/routes.xml
<routes xmlns="routes"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="routes validation/routes.xsd">
 <route name="humax1" enabled="false">
    <host>192.168.16.170</host>
    <port>5005</port>
  </route>
 <route name="humax2" enabled="false">
    <host>192.168.16.145</host>
    <port>5005</port>
  </route>
 <route name="humax3" enabled="false">
    <host>192.168.19.119</host>
    <port>5005</port>
  </route>
</routes>
