=== sys-git/epyrpc/test/config/invalidIntegration/master/config/validation/peerInfo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
 elementFormDefault="qualified"
 targetNamespace="peerInfo"
 xmlns:peerInfo = "peerInfo">
  <xs:element name="peerInfo">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="peerInfo:attributes"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="attributes">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="peerInfo:attribute" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="attribute">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="name" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="envserverHost" />
                    <xs:enumeration value="envserverPort" />
                    <xs:enumeration value="reboot.timeout" />
                    <xs:enumeration value="reboot.cmd.signal" />
                    <xs:enumeration value="reboot.usr.ssh" />
                    <xs:enumeration value="reboot.psw.ssh" />
                    <xs:enumeration value="reboot.cmd.ssh" />
                    <xs:enumeration value="reboot.port.ssh" />
                    <xs:enumeration value="reboot.usr.pwr" />
                    <xs:enumeration value="reboot.psw.pwr" />
                    <xs:enumeration value="reboot.host.pwr" />
                    <xs:enumeration value="reboot.port.pwr" />
                    <xs:enumeration value="reboot.cmd.pwr" />
                    <xs:enumeration value="reboot.quit.pwr" />
                </xs:restriction>
            </xs:simpleType>
          </xs:attribute>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== sys-git/epyrpc/test/config/rebootSSH/config/peerInfo.xml
<peerInfo
    xmlns="peerInfo"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="peerInfo validation/peerInfo.xsd">
    <attributes>
        <attribute name="reboot.usr.ssh">test</attribute>
        <attribute name="reboot.psw.ssh">test</attribute>
        <attribute name="reboot.port.ssh">2022</attribute>
        <attribute name="reboot.cmd.ssh">reboot me please</attribute>
        <attribute name="reboot.usr.pwr">test-pwd</attribute>
        <attribute name="reboot.psw.pwr">test-pwd</attribute>
        <attribute name="reboot.host.pwr">127.0.0.1</attribute>
        <attribute name="reboot.port.pwr">2024</attribute>
        <attribute name="reboot.cmd.pwr">reboot me now</attribute>
    </attributes>
</peerInfo>

=== sys-git/epyrpc/test/config/rebootPowerController/config/peerInfo.xml
<peerInfo
    xmlns="peerInfo"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="peerInfo validation/peerInfo.xsd">
    <attributes>
        <attribute name="reboot.usr.pwr">test-pwr</attribute>
        <attribute name="reboot.psw.pwr">test-pwr</attribute>
        <attribute name="reboot.host.pwr">127.0.0.1</attribute>
        <attribute name="reboot.port.pwr">2024</attribute>
        <attribute name="reboot.cmd.pwr">power off port 1</attribute>
        <attribute name="reboot.quit.pwr">QUIT</attribute>
    </attributes>
</peerInfo>

=== sys-git/epyrpc/test/config/executionOrganiser/config/peerInfo.xml
<peerInfo
    xmlns="peerInfo"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="peerInfo validation/peerInfo.xsd">
    <attributes>
        <attribute name="envserverHost">127.0.0.1</attribute>
        <attribute name="envserverPort">9595</attribute>
        <attribute name="reboot.cmd.signal">reboot -f</attribute>
        <attribute name="reboot.usr.ssh">test</attribute>
        <attribute name="reboot.psw.ssh">test</attribute>
        <attribute name="reboot.port.ssh">2022</attribute>
        <attribute name="reboot.cmd.ssh">reboot me please</attribute>
        <attribute name="reboot.usr.pwr">test-pwr</attribute>
        <attribute name="reboot.psw.pwr">test-pwr</attribute>
        <attribute name="reboot.host.pwr">127.0.0.1</attribute>
        <attribute name="reboot.port.pwr">2024</attribute>
        <attribute name="reboot.cmd.pwr">power off port 1</attribute>
        <attribute name="reboot.quit.pwr">QUIT</attribute>
        <attribute name="reboot.timeout">1</attribute>
    </attributes>
</peerInfo>
