=== sys-git/epyrpc/test/config/resultWorkerMasterDb/config/validation/resultWorker.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="resultWorker" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns1="resultWorker">
  <xs:import namespace="http://www.w3.org/2001/XMLSchema-instance" schemaLocation="xsi.xsd"/>
  <xs:element name="resultWorker">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ns1:output"/>
        <xs:element ref="ns1:customLogFilters"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="output">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ns1:fileSystem"/>
        <xs:element ref="ns1:sqlLite"/>
        <xs:element ref="ns1:trmsLoggers"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="fileSystem">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ns1:location"/>
        <xs:element ref="ns1:clear"/>
        <xs:element ref="ns1:archive"/>
      </xs:sequence>
      <xs:attribute name="enabled" use="required" type="xs:boolean"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="filename" type="xs:NCName"/>
  <xs:element name="sqlLite">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ns1:location"/>
        <xs:element ref="ns1:clear"/>
      </xs:sequence>
      <xs:attribute name="enabled" use="required" type="xs:boolean"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="trmsLoggers">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="ns1:trms"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="trms">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ns1:url"/>
        <xs:element type="xs:string" name="username" />
        <xs:element type="xs:string" name="password" />
      </xs:sequence>
      <xs:attribute name="enabled" use="required" type="xs:boolean"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="url" type="xs:anyURI"/>
  <xs:element name="location">
    <xs:simpleType>
        <xs:restriction base="xs:string">
            <xs:pattern value="(\.|[\.]{0,2}/[a-zA-Z0-9_\-/\.]+)$"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="clear" type="xs:boolean"/>
  <xs:element name="archive">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name">
          <xs:simpleType>
              <xs:restriction base="xs:string">
                  <xs:pattern value="[a-zA-Z0-9_\.]+" />
              </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="format">
          <xs:simpleType>
              <xs:restriction base="xs:string">
                  <xs:enumeration value="zip" />
                  <xs:enumeration value="tar" />
                  <xs:enumeration value="tar.gz" />
                  <xs:enumeration value="tgz" />
              </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element ref="ns1:location" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="customLogFilters">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ns1:customLogFilter" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="customLogFilter">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="location" />
        <xs:element name="filters">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="ns1:filter" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="filter">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="ns1:filterBody">
          <xs:attribute name="type" use="required">
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:enumeration value="literal"/>
                <xs:enumeration value="regex"/>
              </xs:restriction>
            </xs:simpleType>
          </xs:attribute>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="filterBody">
    <xs:restriction base="xs:string">
      <xs:pattern value=".+" />
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== sys-git/epyrpc/test/config/distributorTestMultIter/config/resultWorker.xml
<resultWorker
    xmlns="resultWorker"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="resultWorker validation/resultWorker.xsd">
    <output>
        <fileSystem enabled="true">
            <location>/tmp/results</location>
            <clear>true</clear>
            <archive>
                <name>resultsPackage</name>
                <format>tar.gz</format>
                <location>/tmp/results</location>
            </archive>
        </fileSystem>
        <sqlLite enabled="true">
            <location>/tmp/results/result.sqlite3</location>
            <clear>true</clear>
        </sqlLite>
        <trmsLoggers>
            <trms enabled="false">
                <url>https://devint-trms/trms</url>
                <username>blah</username>
                <password>blah</password>
            </trms>
            <trms enabled="false">
                <url>https://devint-trms/trms</url>
                <username>blah</username>
                <password>blah</password>
            </trms>
        </trmsLoggers>
    </output>
    <customLogFilters>
        <customLogFilter>
            <location>/tmp/blah</location>
            <filters>
                <filter type="literal">result.log</filter>
            </filters>
        </customLogFilter> 
        <customLogFilter>
            <location>/tmp</location>
            <filters>
                <filter type="regex">customLog[0-9]+\.log</filter>
                <filter type="literal">blah.log</filter>
            </filters>
        </customLogFilter> 
    </customLogFilters>
</resultWorker>

=== sys-git/epyrpc/test/config/resultWorkerTRMS/config/resultWorker.xml
<resultWorker
    xmlns="resultWorker"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="resultWorker validation/resultWorker.xsd">
    <output>
	    <fileSystem enabled="false">
	        <location>/tmp/tas/results</location>
	        <clear>true</clear>
            <archive>
                <name>resultsPackage</name>
                <format>tar.gz</format>
                <location>/tmp/results</location>
            </archive>
	    </fileSystem>
        <sqlLite enabled="false">
            <location>./result.sqlite3</location>
            <clear>true</clear>
        </sqlLite>
        <trmsLoggers>
            <trms enabled="true">
                <url>https://devint-trms/trms</url>
                <username>blah</username>
                <password>blah</password>
            </trms>
        </trmsLoggers>
    </output>
    <customLogFilters></customLogFilters>
</resultWorker>

=== sys-git/epyrpc/test/config/resultWorkerNoClear/config/resultWorker.xml
<resultWorker
    xmlns="resultWorker"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="resultWorker validation/resultWorker.xsd">
    <output>
	    <fileSystem enabled="true">
	        <location>./.tas/results</location>
	        <clear>false</clear>
            <archive>
                <name>resultsPackage</name>
                <format>tar.gz</format>
                <location>./.tas/results</location>
            </archive>
	    </fileSystem>
        <sqlLite enabled="true">
            <location>./result.sqlite3</location>
            <clear>false</clear>
        </sqlLite>
        <trmsLoggers>
            <trms enabled="true">
                <url>https://devint-trms/trms</url>
                <username>blah</username>
                <password>blah</password>
            </trms>
            <trms enabled="true">
                <url>https://devint-trms/trms</url>
                <username>blah</username>
                <password>blah</password>
            </trms>
        </trmsLoggers>
    </output>
    <customLogFilters></customLogFilters>
</resultWorker>

=== sys-git/epyrpc/test/config/resultWorkerSQLLite/config/resultWorker.xml
<resultWorker
    xmlns="resultWorker"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="resultWorker validation/resultWorker.xsd">
    <output>
	    <fileSystem enabled="false">
	        <location>/tmp/tas/results</location>
	        <clear>true</clear>
            <archive>
                <name>resultsPackage</name>
                <format>tar.gz</format>
                <location>/tmp/tas/results</location>
            </archive>
	    </fileSystem>
        <sqlLite enabled="true">
            <location>./result.sqlite3</location>
            <clear>true</clear>
        </sqlLite>
        <trmsLoggers>
            <trms enabled="false">
                <url>https://devint-trms/trms</url>
                <username>blah</username>
                <password>blah</password>
            </trms>
            <trms enabled="false">
                <url>https://devint-trms/trms</url>
                <username>blah</username>
                <password>blah</password>
            </trms>
        </trmsLoggers>
    </output>
    <customLogFilters></customLogFilters>
</resultWorker>
